config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  get '/manage_products/', to: 'products#manage'
  get 'checkout/:product_id', to: 'checkout#create', as: 'checkout_product_id'
  post '/checkout/create', to: 'checkout#create'
  # root 'products#index'
  devise_for :users
  resources :products
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end

  def show
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<%= stylesheet_link_tag 'home.css' %>

<body id="background" class="m-2">
<div class="m-2">
  <div class="card">
    <div class="card-header">
      <!--      <h1 id="welcome_title">User Authentication</h1>-->

      <div>

        <div id="nav_logout">
          <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link btn btn-danger btn-sm" %>
            </li>
            |
            <li>
              <%= link_to 'Edit profile', edit_user_registration_path, class: "navbar-link btn btn-primary btn-sm" %>
            </li>
          </ul>
        </div>

      </div>

    </div>
    <br>
    <div class="card-body">
      <p>
      </p>
      <div>
        <h4>Welcome <strong><%= current_user.name %></strong></h4>
      </div>

      <div>
        You are Logged in as <strong><%= current_user.email %></strong>.
      </div>
      <br>
      <div>

      </div>
      <br>
      <div>
        <%= link_to "Manage Products", manage_products_path, class: 'btn btn-info btn-sm' %>
      </div>
      <br>
      <div>

      </div>
      <br>


      <div>
        <%= link_to 'Show Users', users_path, class: "navbar-link btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>
</body>
<%# if user_signed_in? %>

<%#= current_user.roles.pluck(:name) %>

<!--  Are you admin? <%#= current_user.admin? %>-->
<%#= current_user.roles.pluck(:name) %>
<!--.has role? for using rolify-->
<!--Are you admin? <%#= current_user.has_role? :admin %>-->

<%# else %>
<!--  <%#= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |-->
<%#= link_to "Login", new_user_session_path, class: "navbar-link"  %>
<%# end %>
<%# end %>