config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  get '/manage_products/', to: 'products#manage'
  get 'checkout/:product_id', to: 'checkout#create', as: 'checkout_product_id'
  post '/checkout/create', to: 'checkout#create'
  # root 'products#index'
  devise_for :users
  resources :products
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy, :manage]

  # GET /products or /products.json
  def index
    @products = Product.all
    # @users = User.all
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit

    @product = Product.find(params[:id])
    # return if user_owns_product?
    #
    # @product = current_user.product.build
    # redirect_to products_path, flash: { error: 'You are not the owner of that post!' }

  end

  # POST /products or /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # for a user to manage their existing products

  def manage
    @products = current_user.products
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  # def set_product
  #   @product = Product.find(params[:id])
  # end

  def user_owns_product?
    @product.user == current_user
  end

  # Only allow a list of trusted parameters through.

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= stylesheet_link_tag 'home.css' %>
<body class="m-2">
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_details">
    <%= form.label :name, style: "display: block", class: 'form_field' %>
    <%= form.text_field :name, class: 'w-100' %>
  </div>
<br>
  <div class="form_details">
    <%= form.label :price, style: "display: block", class: 'form_field' %>
    <%= form.number_field :price, class: 'w-100' %>
  </div>
<br>
  <div class="form_details">
    <%= form.submit "Update", class: 'btn btn-success btn-sm' %>
  </div>
<% end %>
</body>

app/views/products/_product.html.erb
<%= stylesheet_link_tag 'home.css' %>
<body class="m-2">
<div id="<%= dom_id product %>" class="border border-secondary">
  <div class="m-2">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>
  </div>
</div>
</body>

app/views/products/edit.html.erb
<%= stylesheet_link_tag 'home.css' %>
<body class="m-2">
<div class="edit_card">
  <div class="card bg-light " style="width: 30rem;">
    <div class="m-2">
      <h1 class="card-header">Edit product</h1><br>
      <div class="card-body">
        <div id="form_details">
          <%= render "form", product: @product %>
        </div>
      </div>
      <br>
      <div id="show_back_card" class="card-footer">
        <%= link_to "Show this product", @product, class: 'btn btn-primary btn-sm' %> |
        <%= link_to "Back to products", products_path, class: 'btn btn-primary btn-sm' %>
      </div>
    </div>
  </div>
</div>
</body>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>
<%= stylesheet_link_tag 'home.css' %>

<h1 id="products" class="bg-info">Products</h1>
<br>
<div>
  <% @products.each do |product| %>
    <%= render product %>
    <p id="show_product"><%= link_to "Show Product", product, class: 'btn btn-success btn-sm' %></p>
  <% end %>
  <p><%= link_to "New product", new_product_path, class: 'btn btn-primary btn-sm' %></p>
  <p><%= link_to "Home", welcome_index_path, class: 'btn btn-secondary btn-sm' %></p>
</div>

app/views/products/manage.html.erb
<p style="color: green"><%= notice %></p>
<%= stylesheet_link_tag 'home.css' %>
<body class="m-2">
<h1 id="product_title" class="bg-info">Manage Products</h1>
<br>
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Payment</th>
    <th>Show Product Details</th>
    <th>Edit Product Details</th>
    <th>Delete Product</th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
<!--      <td><%#= product.content %></td>-->
      <td><%= button_to "Payment", checkout_create_path(product_id: product.id), remote: true, class: 'btn btn-success btn-sm' %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to "New product", new_product_path, class: 'btn btn-primary btn-sm', id: 'new_manage' %> |
<%= link_to "Home", welcome_index_path, class: 'btn btn-secondary btn-sm' %>
</body>

app/views/products/new.html.erb
<%= stylesheet_link_tag 'home.css' %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>
<%= stylesheet_link_tag 'home.css' %>
<body class="m-2">


<%= render @product %>
<br>
<div>
  <span>
  <%= link_to "Edit this product", edit_product_path(@product), class: 'btn btn-primary btn-sm' %> |
    <%= link_to "Back to products", manage_products_path, class: 'btn btn-primary btn-sm' %> |
    <%= link_to "Home", welcome_index_path, class: 'btn btn-secondary btn-sm' %>
    <%= link_to "Delete this product", product_path, method: :delete, class: 'btn btn-danger btn-sm', id: 'del_show' %>
  </span>
</div>
</body>